### ISSUE TITLE
Cannot install on Arch Linux (Python 3.7+)

### ISSUE THREAD

**Issue by Quoteme** [pwittchen/spotify-cli-linux#32] opened 2018-12-29 02:46 UTC
I tried again and again. I even installed python-dbus, as suggested in the readme.md. But I keep getting this error:
```
 > pip install spotify-cli-linux --user
Collecting spotify-cli-linux
  Using cached https://files.pythonhosted.org/packages/97/50/9bcf63c522816031be72b7f9a03eabe383f0dd00e0e613461dd89fdb58c8/spotify-cli-linux-1.2.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-vuqnp9nu/spotify-cli-linux/setup.py", line 3, in <module>
        from spotifycli.spotifycli import __doc__
      File "/tmp/pip-install-vuqnp9nu/spotify-cli-linux/spotifycli/spotifycli.py", line 9, in <module>
        from version import __version__
    ModuleNotFoundError: No module named 'version'

```
pip list gives me this list:
```
1 > pip list
Package      Version         
------------ ----------------
appdirs      1.4.3           
btrfsutil    1.1.0           
CacheControl 0.12.5          
cffi         1.11.5          
chardet      3.0.4           
colorama     0.4.1           
distlib      0.2.8           
distro       1.3.0           
greenlet     0.4.15          
html5lib     1.0.1           
idna         2.8             
lensfun      0.3.2           
lockfile     0.12.2          
lxml         4.2.5           
msgpack      0.5.6           
numpy        1.15.4          
packaging    18.0            
pep517       0.3             
Pillow       5.3.0           
pip          18.1            
progress     1.4             
pycparser    2.19            
PyGObject    3.30.4          
pynvim       0.3.1           
pyparsing    2.3.0           
pytoml       0.1.20          
pywal        3.2.1           
Reflector    2018.3.3.22.1.34
requests     2.20.1          
retrying     1.3.3           
setuptools   40.6.3          
six          1.12.0          
team         1.0             
urllib3      1.24.1          
webencodings 0.5.1           
youtube-dl   2018.12.17
```

**Comment by pwittchen** [comment] 2018-12-29 08:19
Hm, it's strange. It looks like the script doesn't see version.py file.
Which python and pip version are you using?

sob., 29 gru 2018, 03:46: Luca-Leon Happel <notifications@github.com>
napisał(a):

**Comment by rhodium45** [comment] 2018-12-29 17:45
Same error on my machine. I use Python 3.7 and pip 18.1.

**Comment by pwittchen** [comment] 2018-12-30 09:05
Does it happen on Arch only? I tested it on the latest Ubuntu LTS and it
worked fine. Maybe getting rid of version.py file or changing the way of
importing it would help.

sob., 29 gru 2018, 18:45: Drilon Buzuku <notifications@github.com>
napisał(a):

**Comment by pwittchen** [comment] 2019-01-02 23:03
This maybe the solution for this problem: https://stackoverflow.com/questions/32423793/importerror-no-module-named-version

I'll check it during the day and possibly release next version with the fix.

**Comment by pwittchen** [comment] 2019-01-03 13:52
It's strange, when I changed:
```
from version import __version__
```
to:
```
from .version import __version__
```
like in suggested threads, then it didn't work on my machine with Ubuntu and I got the same errors as you.

**Comment by pwittchen** [comment] 2019-01-03 14:00
@Quoteme @rhodium45:

Please try to install this package in the following, alternative way:

```
git clone https://github.com/pwittchen/spotify-cli-linux.git
cd spotify-cli-linux/
pip install -e .
```

I hope it helps.

**Comment by pwittchen** [comment] 2019-01-05 10:43
Ok, I was able to reproduce this issue on my machine. It's related to Python version - not Arch. Since Python 3.7 notation without a dot during the import is invalid in this case. I just need to find a way to make this script working on all Python versions or create separate releases for different versions.

**Comment by pwittchen** [comment] 2019-01-05 10:55
It should be fixed in the latest release: [1.2.4](https://github.com/pwittchen/spotify-cli-linux/releases/tag/v1.2.4).
Please upgrade your version with: `pip install spotify-cli-linux --upgrade`
In case, you still have this problem, we can re-open this issue or create a new one

**Comment by hsantanna** [comment] 2019-02-07 16:16
Now it can be installed, but won't run because spotifycli/spotifycli.py line 63, does:

>     command = raw_input('spotify > ')
> NameError: name 'raw_input' is not defined

That's because raw_input is python2 and won't work with python3.

**Comment by pwittchen** [comment] 2019-02-07 16:21
@hsantanna Thanks for reporting this. I'll have a look at it.

**Comment by pwittchen** [comment] 2019-02-07 21:14
It's strange, because it worked fine for me on both Python versions. Nevertheless, I've added fix here: https://github.com/pwittchen/spotify-cli-linux/commit/cf8df53e709dc250adb903395a8cf743b174f870.
You can upgrade script and tell me if the problem still occurs.

**Closed by pwittchen** 2019-02-07 21:14 UTC
Labels: bug
