### ISSUE TITLE
Error when running 

### ISSUE THREAD

**Issue by giatrakosg** [pwittchen/spotify-cli-linux#2] opened 2017-03-27 19:55 UTC
After running the following command I got this error.
![error](https://cloud.githubusercontent.com/assets/22731222/24375264/611ebb10-1340-11e7-9843-b40a0348dd19.png)

**Comment by pwittchen** [comment] 2017-03-27 20:50
Hi,

Thanks for reporting that issue.
It looks you don't have `dbus` module installed.
I don't know what Linux distro you're using, but in the case of Ubuntu, you can try running:

```
sudo apt-get install python-dbus
```

If you are using another distro, try to install `python-dbus` with your package manager.

**Comment by giatrakosg** [comment] 2017-03-27 21:23
Hi ,
thanks for the help the issue was fixed.Great app,works great.

PS: I think adding an option to show the next song would be useful

**Comment by pwittchen** [comment] 2017-03-27 21:27
Great!

I've created issue #3 for mentioned suggestion. We can figure it out in the future.
The problem is solved, so I'm closing this issue. :-)

Regards,
Piotr

**Closed by pwittchen** 2017-03-27 21:27 UTC

**Comment by pwittchen** [comment] 2017-03-27 21:37
I've added [solving problems](https://github.com/pwittchen/spotify-cli-linux#solving-problems) section to `README.md` in case if someone else will have the same problem in the future.

**Comment by tnguyen14** [comment] 2018-04-16 20:09
@pwittchen is there a way to install dbus on Mac? I tried `brew install dbus` and it installed successfully, but I still got the same error.

**Comment by pwittchen** [comment] 2018-04-16 20:50
@tnguyen14: as the project name says, it's spotify-cli-**linux**. It's for Linux and doesn't work on Mac. If you want to have something like that on Mac, try [shpotify](https://github.com/hnarayanan/shpotify) project.
